=== gosia4/XML-task-5/XMLSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   xmlns:p="http://www.example.com"
		   xmlns:c="http://www.example.com"
		   targetNamespace="http://www.example.com"
		   elementFormDefault="qualified"
		   >
	<xs:include schemaLocation="cNamespace.xsd"/>
	<xs:include schemaLocation="pNamespace.xsd"/>
	<!--<xs:import schemaLocation="pNamespace.xsd" namespace="http://www.example.com"/>
	<xs:import schemaLocation="cNamespace.xsd" namespace="http://www.example.com"/>
-->
	
	<xs:element name="composers">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="documentInformation" type="c:documentInformationType" maxOccurs="1"/>
				<xs:element name="composer" type="c:composerType" maxOccurs="unbounded"/>
				<xs:element name="publisher" type="p:publisherType" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
		<xs:key name="publisher_id">
				<xs:selector xpath="./p:publisher"/>
				<xs:field xpath="@id"/>
			</xs:key>
			<xs:keyref name="id_reference_piece" refer="p:publisher_id">
				<xs:selector xpath="./c:composer/c:pieces/c:piece/c:publisher"/>
				<xs:field xpath="@nr"/>
			</xs:keyref>
			<xs:keyref name="id_reference_book" refer="p:publisher_id">
				<xs:selector xpath="./c:composer/c:books/c:book/c:publisher"/>
				<xs:field xpath="@nr"/>
			</xs:keyref>
	</xs:element>
	
	<xs:complexType name="documentInformationType">
		<xs:sequence>
			<xs:element name="author">
				<xs:complexType>
					<xs:sequence>
						<xs:element type="c:studentName" name="student_name"/>
						<xs:element type="c:surnameType" name="surname"/>
						<xs:element type="c:studentIDType" name="studentID"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element type="xs:date" name="creationDate"/>
			<xs:element type="xs:date" name="lastModificationDate"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="composerType">
			<xs:sequence>
				<xs:element name="person" type="c:personType"/>
				<xs:element type="c:first_nameType" name="first_name" maxOccurs="3" minOccurs="1"/>
				<xs:element type="c:surnameType" name="surname"/>
				<xs:element type="c:nationalityType" name="nationality"/>
				<xs:element type="c:lifespanType" name="lifespan"/>
				<xs:element type="c:addressType" name="address"/>
				<xs:element type="c:piecesType" name="pieces"/>
				<xs:element type="c:booksType" name="books"/>
			</xs:sequence>
		<xs:attributeGroup ref="c:composerAttributes"/>
	</xs:complexType>


	<xs:complexType name="piecesType">
			<xs:sequence>
				<xs:element name="piece" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:all>
							<xs:element type="c:pieceNameType" name="name"/>
							<xs:element type="c:tonationType" name="tonation"/>
							<xs:element type="c:opType" name="op" minOccurs="0" maxOccurs="1"/>
							<xs:element type="c:noType" name="nr" minOccurs="0" maxOccurs="1"/>
							<xs:element type="c:levelType" name="level"/>
							<xs:element type="c:instrumentsType" name="instruments"/>
							<xs:element type="c:publisherPriceType" name="publisher"/>
						</xs:all>
						<xs:attribute type="c:noType" name="nr" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>

	
		<xs:complexType name="booksType">
			<xs:sequence>
				<xs:element name="book" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="c:contentType" name="content"/>
							<xs:element type="c:pagesType" name="amount_of_pages"/>
							<xs:element type="c:ISBNtype" name="ISBN"/>
							<xs:element type="c:publisherPriceType" name="publisher">
								<!--<xs:complexType>
									<xs:all>
										<xs:element type="p:publisherType" name="publisher"/>
										<xs:element type="c:priceType" name="price"/>
									</xs:all>
								</xs:complexType>-->
							</xs:element>
						</xs:sequence>
						<xs:attribute type="c:noType" name="no" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>

	

	<xs:attributeGroup name="composerAttributes">
		<xs:attribute name="id" type="c:composerIdType" use="required"/>
		<xs:attribute name="born" type="c:composerBornType" use="required"/>
	</xs:attributeGroup>

	<xs:complexType name="personType">
			<xs:attribute type="c:genderType" name="gender" use="optional"/>
		</xs:complexType>



	<xs:complexType name="addressType">
		<xs:choice>
			<xs:element name="city" type="c:cityType"/>
			<xs:element name="ZIPcode" type="c:ZIPcodeType"/>
		</xs:choice>
	</xs:complexType>

	<xs:complexType name="publisherPriceType">
		<xs:sequence>
			<xs:element type="c:priceCurType" name="price"/>
		</xs:sequence>
		<xs:attribute type="p:publisherIdType" name="nr" use="required"/>
	</xs:complexType>

	
	
	<xs:complexType name="publisherType">
		<xs:sequence>
			<xs:element type="p:publisherNameType" name="namePublisher"/>
		</xs:sequence>
		<xs:attribute type="p:publisherIdType" name="id" use="required"/>
	</xs:complexType>



</xs:schema>

=== gosia4/XML-task-5/changed(1).xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<c	xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="composers XMLSchema.xsd" xmlns="composers">
	<p	xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="composers XMLSchema.xsd" xmlns="composers">
	-->
<?xml-stylesheet type = "text/css" href="new 1.css"?>
<composers xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="http://www.example.com XMLSchema.xsd" xmlns="http://www.example.com">
			
			<documentInformation>
				<author>
					<student_name>Malgorzata</student_name>
					<surname>Komorowska</surname>
					<studentID>242218</studentID>
				</author>
				<creationDate>2022-10-11</creationDate>
				<lastModificationDate>2022-10-25</lastModificationDate>
			</documentInformation>
			<composer id="1234" born="1810">
				<person gender="male"/>
				<first_name>Fryderyk</first_name>
				<surname>Chopin</surname>
				<nationality>Poland</nationality>
				<lifespan>39</lifespan>
				<address>
					<city>Zelazowa Wola</city>
				</address>
				<pieces>
					<piece nr="1">
						<name>Nokturn</name>
						<tonation>c-minor</tonation>
						<level>hard</level>
						<instruments>piano</instruments>
						<publisher nr="2">
							<price cur="PLN">19.99</price>
						</publisher>
					</piece>
					<piece nr="21">
						<name>Ty</name>
						<tonation>c-minor</tonation>
						<op>45</op>
						<level>very hard</level>
						<instruments>tak nie i to</instruments>
						<publisher nr="2">
							<price cur="USD">0</price>
						</publisher>
					</piece>
					<piece nr="3">
						<name>Etude</name>
						<tonation>c-minor</tonation>
						<op>10</op>
						<nr>4</nr>
						<level>very hard</level>
						<instruments>piano</instruments>
						<publisher nr="2">
							<price cur="USD">3.00</price>
						</publisher>
					</piece>
					<piece nr="4">
						<name>Nokturn</name>
						<tonation>a-minor</tonation>
						<level>medium</level>
						<instruments>piano</instruments>
						<publisher nr="4">
							<price cur="PLN">15.99</price>
						</publisher>
					</piece>
					<piece nr="5">
						<name>Waltz</name>
						<tonation>a-minor</tonation>
						<level>easy</level>
						<instruments>piano</instruments>
						<publisher nr="4">
							<price cur="PLN">8.99</price>
						</publisher>
					</piece>
				</pieces>

				<books>
					<book no="1">
						<content>Nokturn</content>
						<amount_of_pages>56</amount_of_pages>
						<ISBN>341-95-745-0781-1</ISBN>
						<publisher nr="2">
							<price cur="PLN">39.99</price>
						</publisher>
					</book>
					<book no="18">
						<content>Ja</content>
						<amount_of_pages>123</amount_of_pages>
						<ISBN>330-55-987-1234-2</ISBN>
						<publisher nr="2">
							<price cur="USD">90</price>
						</publisher>
					</book>
					<book no="3">
						<content>Songs</content>
						<amount_of_pages>36</amount_of_pages>
						<ISBN>671-94-785-0781-1</ISBN>
						<publisher nr="2">
							<price cur="PLN">19.99</price>
						</publisher>
					</book>
					<book no="4">
						<content>Etudes</content>
						<amount_of_pages>56</amount_of_pages>
						<ISBN>241-05-745-4891-2</ISBN>
						<publisher nr="3">
							<price cur="PLN">39.99</price>
						</publisher>
					</book>
				</books>
			</composer>


			<composer id="7854" born="1756">
				<person gender="male"/>
				<first_name>Wolfgang</first_name>
				<!-- <first_name>Amadeusz</first_name> -->
				<surname>Mozart</surname>
				<nationality>Austria</nationality>
				<lifespan>35</lifespan>
				<address>
					<city>Salzburg</city>
				</address>
				<pieces>
					<piece nr="6">
						<name>Symphony</name>
						<tonation>g-minor</tonation>
						<nr>40</nr>
						<level>very hard</level>
						<instruments>violin viola cello double_bass french_corn trumpet oboe drums</instruments>
						<publisher nr="2">
							<price cur="EUR">14.99</price>
						</publisher>
					</piece>
					<piece nr="7">
						<name>Piano Concert</name>
						<tonation>c-minor</tonation>
						<nr>24</nr>
						<level>hard</level>
						<instruments>piano violin viola cello double_bass french_corn trumpet oboe drums</instruments>
						<publisher nr="6">
							<price cur="EUR">9.39</price>
						</publisher>
					</piece>
					<piece nr="8">
						<name>Sonate</name>
						<tonation>f-minor</tonation>
						<nr>4</nr>
						<level>medium</level>
						<instruments>piano</instruments>
						<publisher nr="6">
							<price cur="USD">3</price>
						</publisher>
					</piece>
					<piece nr="9">
						<name>Symphony</name>
						<tonation>Es-major</tonation>
						<nr>5</nr>
						<level>hard</level>
						<instruments>violin viola cello double_bass french_corn trumpet oboe drums</instruments>
						<publisher nr="2">
							<price cur="EUR">20.99</price>
						</publisher>
					</piece>
					<piece nr="10">
						<name>Piano Concert</name>
						<tonation>C-major</tonation>
						<level>hard</level>
						<instruments>piano violin viola cello double_bass french_corn trumpet oboe drums</instruments>
						<publisher nr="2">
							<price cur="PLN">17.99</price>
						</publisher>
					</piece>
				</pieces>

				<books>
					<book no="5">
						<content>Sonates</content>
						<amount_of_pages>150</amount_of_pages>
						<ISBN>927-95-790-3456-1</ISBN>
						<publisher nr="5">
							<price cur="PLN">89.99</price>
						</publisher>
					</book>
					<book no="6">
						<content>Arias</content>
						<amount_of_pages>82</amount_of_pages>
						<ISBN>289-45-987-1098-2</ISBN>
						<publisher nr="2">
							<price cur="EUR">25.99</price>
						</publisher>
					</book>
					<book no="7">
						<content>Songs</content>
						<amount_of_pages>50</amount_of_pages>
						<ISBN>251-95-999-5681-1</ISBN>
						<publisher nr="2">
							<price cur="PLN">39.99</price>
						</publisher>
					</book>
					<book no="8">
						<content>Violin Concerts</content>
						<amount_of_pages>200</amount_of_pages>
						<ISBN>301-11-745-8951-1</ISBN>
						<publisher nr="2">
							<price cur="EUR">49.99</price>
						</publisher>
					</book>
				</books>
			</composer>


			<composer id="8674" born="1770">
				<person gender="male"/>
				<first_name>Ludwig</first_name>
				<!-- <first_name>Van</first_name> -->
				<surname>Beethoven</surname>
				<nationality>Garmany</nationality>
				<lifespan>57</lifespan>
				<address>
					<city>Bonn</city>
				</address>
				<pieces>
					<piece nr="11">
						<name>Sonate</name>
						<tonation>cis-minor</tonation>
						<level>easy</level>
						<instruments>piano</instruments>
						<publisher nr="2">
							<price cur="PLN">15.99</price>
						</publisher>
					</piece>
					<piece nr="12">
						<name>Symphony</name>
						<tonation>c-minor</tonation>
						<nr>5</nr>
						<level>hard</level>
						<instruments>violin viola cello double_bass french_corn trumpet oboe drums</instruments>
						<publisher nr="2">
							<price cur="EUR">12.39</price>
						</publisher>
					</piece>
					<piece nr="13">
						<name>Sonate</name>
						<tonation>G-major</tonation>
						<nr>8</nr>
						<level>very hard</level>
						<instruments>piano</instruments>
						<publisher nr="2">
							<price cur="USD">2.57</price>
						</publisher>
					</piece>

					<piece nr="14">
						<name>String Quartet</name>
						<tonation>D-major</tonation>
						<nr>3</nr>
						<level>hard</level>
						<instruments>violin viola cello double_bass</instruments>
						<publisher nr="2">
							<price cur="PLN">19.99</price>
						</publisher>
					</piece>
					<piece nr="15">
						<name>String Quartet</name>
						<tonation>G-major</tonation>
						<nr>3</nr>
						<level>very hard</level>
						<instruments>violin viola cello double_bass</instruments>
						<publisher nr="2">
							<price cur="PLN">34.99</price>
						</publisher>
					</piece>
				</pieces>
				<books>
					<book no="9">
						<content>Irish Songs</content>
						<amount_of_pages>75</amount_of_pages>
						<ISBN>444-95-745-1081-1</ISBN>
						<publisher nr="2">
							<price cur="PLN">39.99</price>
						</publisher>
					</book>
					<book no="10">
						<content>Sonates</content>
						<amount_of_pages>78</amount_of_pages>
						<ISBN>412-55-987-1875-9</ISBN>
						<publisher nr="6">
							<price cur="PLN">41.99</price>
						</publisher>
					</book>
					<book no="11">
						<content>Songs</content>
						<amount_of_pages>140</amount_of_pages>
						<ISBN>111-95-745-5781-6</ISBN>
						<publisher nr="2">
							<price cur="PLN">35.99</price>
						</publisher>
					</book>
					<book no="12">
						<content>Variations</content>
						<amount_of_pages>90</amount_of_pages>
						<ISBN>101-78-245-0781-1</ISBN>
						<publisher nr="5">
							<price cur="USD">13.99</price>
						</publisher>
					</book>
				</books>
			</composer>


			<composer id="4567" born="1685">
				<person gender="male"/>
				<first_name>Jan</first_name>
				<!-- <first_name>Sebastian</first_name> -->
				<surname>Bach</surname>
				<nationality>Germany</nationality>
				<lifespan>65</lifespan>
				<address>
					<city>Eisenach</city>
				</address>
				<pieces>
					<piece nr="16">
						<name>Violin Concerto</name>
						<tonation>D-major</tonation>
						<level>hard</level>
						<instruments>violin viola cello double_bass oboe flute drums</instruments>
						<publisher nr="2">
							<price cur="PLN">18.99</price>
						</publisher>
					</piece>
					<piece nr="17">
						<name>Orchestral Suite</name>
						<tonation>C-major</tonation>
						<nr>1</nr>
						<level>very hard</level>
						<instruments>violin viola cello double_bass harpsichord trumpet oboe</instruments>
						<publisher nr="2">
							<price cur="EUR">14.39</price>
						</publisher>
					</piece>
					<piece nr="18">
						<name>Brandenburg Concerto</name>
						<tonation>G-major</tonation>
						<nr>4</nr>
						<level>very hard</level>
						<instruments>piano violin viola cello double_bass</instruments>
						<publisher nr="2">
